#!/usr/bin/env node
/**
 * Anti-Sycophancy Protocol v2.0 — Sync Engine
 *
 * 单一事实源：protocol.md（必须含 YAML frontmatter）
 * 衍生物：SKILL.md, claude-integration/CLAUDE.md
 * 漂移检测目标：examples/, tests/
 *
 * 用法：
 *   node scripts/sync.js                # 默认：生成所有衍生物
 *   node scripts/sync.js --check        # 仅检查漂移，不修改，输出报告
 *   node scripts/sync.js --force        # 强制覆盖（即使有手动修改）
 *   node scripts/sync.js --target SKILL.md  # 只生成指定目标
 *
 * 退出码：
 *   0 = 无漂移或已同步
 *   1 = 检测到漂移（--check 模式）
 *   2 = frontmatter 缺失或 schema 错误
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PROTOCOL = path.join(ROOT, 'protocol.md');
const SKILL = path.join(ROOT, 'SKILL.md');
const CLAUDE = path.join(ROOT, 'claude-integration', 'CLAUDE.md');
const EXAMPLES = path.join(ROOT, 'examples');
const TESTS = path.join(ROOT, 'tests');

// ----- Frontmatter Schema -----

const REQUIRED_FRONTMATTER_FIELDS = [
  'name',
  'version',
  'schema_version',
  'priority_levels',
  'safety_domains',
  'bypass_patterns',
  'generated_outputs',
  'drift_check',
];

// ----- Frontmatter 解析 -----
function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]+?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) {
    return { frontmatter: null, body: null, error: 'Missing or invalid frontmatter (must be at file start, delimited by ---)' };
  }
  const fm = {};
  const lines = match[1].split(/\r?\n/);
  let currentKey = null;
  let currentList = null;
  function coerce(val) {
    if (val === 'true') return true;
    if (val === 'false') return false;
    if (val === 'null') return null;
    if (/^-?\d+$/.test(val)) return parseInt(val, 10);
    if (/^-?\d+\.\d+$/.test(val)) return parseFloat(val);
    return val.replace(/^["']|["']$/g, '');
  }
  for (const line of lines) {
    if (/^[a-z_]+:/.test(line)) {
      const m = line.match(/^([a-z_]+):\s*(.*)$/);
      currentKey = m[1];
      const val = m[2].trim();
      if (val === '' || val === '|' || val === '>') {
        currentList = [];
        fm[currentKey] = currentList;
      } else if (val.startsWith('[') && val.endsWith(']')) {
        const inner = val.slice(1, -1).trim();
        if (inner === '') { fm[currentKey] = []; }
        else { fm[currentKey] = inner.split(',').map(s => coerce(s.trim())); }
        currentList = null;
      } else {
        fm[currentKey] = coerce(val);
        currentList = null;
      }
    } else if (/^\s+-\s+/.test(line) && currentList) {
      const item = line.replace(/^\s+-\s+/, '').trim().replace(/^["']|["']$/g, '');
      currentList.push(coerce(item));
    }
  }
  return { frontmatter: fm, body: match[2], error: null };
}

function validateFrontmatter(fm) {
  const errors = [];
  for (const field of REQUIRED_FRONTMATTER_FIELDS) {
    if (!(field in fm)) {
      errors.push(`Missing required field: ${field}`);
    }
  }
  if (fm.schema_version !== 1) {
    errors.push(`schema_version must be 1, got: ${fm.schema_version}`);
  }
  if (fm.drift_check !== true) {
    errors.push(`drift_check must be true, got: ${fm.drift_check}`);
  }
  if (!Array.isArray(fm.priority_levels) || fm.priority_levels.length !== 5) {
    errors.push(`priority_levels must be array of 5 [P0,P1,P2,P3,P4]`);
  }
  return errors;
}

// ----- 漂移检测 -----

function isAutoGenerated(content) {
  return content.startsWith('# AUTO-GENERATED from protocol.md')
      || content.startsWith('<!-- AUTO-GENERATED')
      || content.startsWith('---')
         && content.includes('AUTO-GENERATED');
}

function checkDrift(filePath, expectedHeader) {
  if (!fs.existsSync(filePath)) {
    return { drift: true, reason: 'file missing' };
  }
  const content = fs.readFileSync(filePath, 'utf8');
  if (!isAutoGenerated(content)) {
    return { drift: true, reason: 'no AUTO-GENERATED marker (likely hand-edited)' };
  }
  if (expectedHeader && !content.includes(expectedHeader)) {
    return { drift: true, reason: 'expected header not found (protocol.md may have changed)' };
  }
  return { drift: false };
}

// ----- 生成 SKILL.md -----

function generateSkillMd(fm, body) {
  // 提取关键章节
  const sections = {
    p0: extractSection(body, '## P0 —', '## P1 —'),
    p1: extractSection(body, '## P1 —', '## P2 —'),
    p2: extractSection(body, '## P2 —', '## P3 —'),
    p3: extractSection(body, '## P3 —', '## P4 —'),
    p4: extractSection(body, '## P4 —', '## 支持模式'),
  };

  const header = `# AUTO-GENERATED from protocol.md — edit protocol.md only
---
name: anti-sycophancy
description: >
  全局反谄媚协议 v${fm.version}。核心目标：证据相同时，结论不随用户立场漂移。
  P0-P4 优先级链，安全优先，立场一致性替代固定比例结构。
  Trigger when: 任何对话（作为全局协议加载），或用户讨论视频脚本/标题/观后感。
source: protocol.md@v${fm.version}
schema_version: 1
---

# 全局反谄媚协议 v${fm.version}

> **核心目标**：在证据相同的情况下，模型结论不随用户表达的立场、身份或偏好改变。

---

## 规则优先级体系

\`\`\`
P0 (安全边界) → P1 (事实与证据) → P2 (不确定性校准) → P3 (完成任务) → P4 (风格)
\`\`\`

- 上级覆盖下级，不可被"支持模式"绕过
- P0 命中时，不完成 P3 任务不算违反 P3
- P0 命中时，支持模式不可激活

---

`;

  return header
    + sections.p0 + '\n---\n'
    + sections.p1 + '\n---\n'
    + sections.p2 + '\n---\n'
    + sections.p3 + '\n---\n'
    + sections.p4 + '\n---\n\n## 支持模式\n\n用户说"切换至温和模式"或"请给我情绪支持"时：\n\n- 只能调整语气和措辞\n- 不能调整：P0 安全边界、P1 事实核验标准、P2 不确定性校准、纠错验证流程\n- P0 命中时支持模式不可激活\n- 下次回复自动恢复默认模式\n';
}

function extractSection(body, startMarker, endMarker) {
  const startIdx = body.indexOf(startMarker);
  if (startIdx === -1) return '';
  const endIdx = body.indexOf(endMarker, startIdx);
  return body.slice(startIdx, endIdx === -1 ? body.length : endIdx).trim();
}

// ----- 主流程 -----

function main() {
  const args = process.argv.slice(2);
  const checkMode = args.includes('--check');
  const forceMode = args.includes('--force');
  const targetArg = args.includes('--target') ? args[args.indexOf('--target') + 1] : null;

  console.log('Anti-Sycophancy Protocol — Sync Engine');
  console.log('=======================================');
  console.log(`Mode: ${checkMode ? 'check' : forceMode ? 'force' : 'sync'}`);
  if (targetArg) console.log(`Target: ${targetArg}`);
  console.log('');

  // 1. 读 protocol.md
  if (!fs.existsSync(PROTOCOL)) {
    console.error(`ERROR: protocol.md not found at ${PROTOCOL}`);
    process.exit(2);
  }
  const protocolContent = fs.readFileSync(PROTOCOL, 'utf8');
  const { frontmatter, body, error } = parseFrontmatter(protocolContent);

  if (error) {
    console.error(`ERROR: ${error}`);
    console.error('protocol.md must start with YAML frontmatter delimited by ---');
    process.exit(2);
  }

  // 2. 验证 frontmatter
  const errors = validateFrontmatter(frontmatter);
  if (errors.length > 0) {
    console.error('ERROR: frontmatter validation failed:');
    for (const e of errors) console.error(`  - ${e}`);
    process.exit(2);
  }

  console.log(`Protocol: ${frontmatter.name}@v${frontmatter.version} (schema ${frontmatter.schema_version})`);
  console.log(`Safety domains: ${frontmatter.safety_domains.join(', ')}`);
  console.log('');

  // 3. 漂移检测
  const targets = [
    { path: SKILL, name: 'SKILL.md', header: 'AUTO-GENERATED from protocol.md' },
    { path: CLAUDE, name: 'claude-integration/CLAUDE.md', header: 'AUTO-GENERATED from protocol.md' },
  ];

  let driftDetected = false;
  for (const t of targets) {
    if (targetArg && t.name !== targetArg) continue;
    const result = checkDrift(t.path, t.header);
    if (result.drift) {
      console.log(`[DRIFT] ${t.name}: ${result.reason}`);
      driftDetected = true;
    } else {
      console.log(`[OK]    ${t.name}`);
    }
  }

  // 4. examples / tests 漂移检测（只检测，不生成）
  if (fs.existsSync(EXAMPLES)) {
    console.log('');
    console.log('Drift check: examples/');
    for (const f of fs.readdirSync(EXAMPLES)) {
      const fp = path.join(EXAMPLES, f);
      if (fs.statSync(fp).isFile() && f.endsWith('.md')) {
        const content = fs.readFileSync(fp, 'utf8');
        const hasMarker = content.includes('protocol.md@v' + frontmatter.version);
        console.log(`  [${hasMarker ? 'OK' : 'DRIFT'}] ${f}`);
        if (!hasMarker) driftDetected = true;
      }
    }
  }
  if (fs.existsSync(TESTS)) {
    console.log('');
    console.log('Drift check: tests/');
    for (const f of fs.readdirSync(TESTS)) {
      const fp = path.join(TESTS, f);
      if (fs.statSync(fp).isFile() && (f.endsWith('.json') || f.endsWith('.js'))) {
        console.log(`  [INFO] ${f}`);
      }
    }
  }

  console.log('');

  if (checkMode) {
    if (driftDetected) {
      console.log('DRIFT DETECTED. Run `node scripts/sync.js` to regenerate.');
      process.exit(1);
    } else {
      console.log('No drift detected. All derived files in sync.');
      process.exit(0);
    }
  }

  if (driftDetected && !forceMode) {
    console.log('Drift detected. Re-run with --force to overwrite, or edit protocol.md and re-sync.');
    process.exit(1);
  }

  // 5. 生成衍生物
  if (!targetArg || targetArg === 'SKILL.md') {
    const skillContent = generateSkillMd(frontmatter, body);
    fs.writeFileSync(SKILL, skillContent, 'utf8');
    console.log(`[GEN] SKILL.md (${skillContent.length} bytes)`);
  }

  if (!targetArg || targetArg === 'claude-integration/CLAUDE.md') {
    // CLAUDE.md 复用 SKILL.md 内容 + 适配 Claude Code 头部
    const skillContent = generateSkillMd(frontmatter, body);
    const claudeHeader = `# AUTO-GENERATED from protocol.md — edit protocol.md only
<!-- source: protocol.md@v${frontmatter.version} | schema_version: ${frontmatter.schema_version} -->\n\n`;
    const claudeContent = claudeHeader + skillContent.replace(/^---[\s\S]+?---\n\n/, '');
    fs.writeFileSync(CLAUDE, claudeContent, 'utf8');
    console.log(`[GEN] claude-integration/CLAUDE.md (${claudeContent.length} bytes)`);
  }

  console.log('');
  console.log('Sync complete.');
}

if (require.main === module) {
  main();
}

module.exports = { parseFrontmatter, validateFrontmatter, checkDrift, generateSkillMd };